import type { Context } from 'hono';
import { z } from 'zod';
export type Bindings={APP_ORIGIN:string;DB:D1Database};
type Ctx=Context<{Bindings:Bindings}>;
const SESSION_SECONDS=12*60*60; // Browser-session cookie, short-lived server session
const ITERATIONS=100000; // Workers Web Crypto limit; revisit for public production.
const encoder=new TextEncoder();
// Letter-based names; letters from any language, combining marks, spaces and common name separators.
export const nameSchema=z.string().trim().transform(x=>x.normalize('NFC').replace(/ +/g,' ')).pipe(z.string().min(2).max(60).regex(/^[\p{L}][\p{L}\p{M}]*(?:[ '\u2019.-][\p{L}][\p{L}\p{M}]*)*$/u,'Use letters and normal name separators only.'));
const passwordSchema=z.string().min(12,'Use at least 12 characters.').max(128).refine(x=>/\p{L}/u.test(x)&&/\p{N}/u.test(x),'Include both letters and numbers.').refine(x=>!/[\u0000-\u001f\u007f]/.test(x),'Control characters are not allowed.');
const emailSchema=z.string().trim().email().max(254).transform(x=>x.toLowerCase());
const registerSchema=z.object({name:nameSchema,email:emailSchema,password:passwordSchema}).strict();
const loginSchema=z.object({email:emailSchema,password:z.string().min(1).max(128)}).strict();
function hex(bytes:Uint8Array){return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
function unhex(s:string){const a=new Uint8Array(s.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}
function randomHex(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a)}
async function sha256(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(s))))}
async function hashPassword(password:string,salt:string,iterations:number){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unhex(salt),iterations},key,256);return hex(new Uint8Array(bits))}
function equal(a:string,b:string){let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0}
const COOKIE='lifevault_session';
function cookie(value:string,clear=false){return COOKIE+'='+value+'; Path=/api/v1; HttpOnly; Secure; SameSite=Strict'+(clear?'; Max-Age=0':'')}
function getCookie(header:string|null|undefined){for(const chunk of (header||'').split(';')){const [key,...rest]=chunk.trim().split('=');if(key===COOKIE)return rest.join('=')}return null}
async function readBody(c:Ctx):Promise<unknown|null>{if(Number(c.req.header('content-length')||0)>4000)return null;try{const raw=await c.req.text();return raw.length<=4000?JSON.parse(raw):null}catch{return null}}
async function throttled(c:Ctx,action:string,max:number){const ip=c.req.header('CF-Connecting-IP')||'unknown',key=await sha256(action+':'+ip),now=Math.floor(Date.now()/1000),windowStart=now-900;await c.env.DB.prepare('INSERT INTO auth_attempts(key,attempts,window_start) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN window_start<? THEN 1 ELSE attempts+1 END,window_start=CASE WHEN window_start<? THEN excluded.window_start ELSE window_start END').bind(key,now,windowStart,windowStart).run();const row=await c.env.DB.prepare('SELECT attempts FROM auth_attempts WHERE key=?').bind(key).first<{attempts:number}>();return (row?.attempts||0)>max}
export type User={id:string;email:string;display_name:string};
const publicUser=(u:User)=>({id:u.id,email:u.email,name:u.display_name});
export async function currentUser(c:Ctx):Promise<User|null>{const token=getCookie(c.req.header('cookie'));if(!token||!/^[a-f0-9]{64}$/.test(token))return null;return c.env.DB.prepare('SELECT u.id,u.email,u.display_name FROM auth_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await sha256(token),Math.floor(Date.now()/1000)).first<User>()}
async function issueSession(c:Ctx,user:User){const token=randomHex(),now=Math.floor(Date.now()/1000);await c.env.DB.prepare('INSERT INTO auth_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(await sha256(token),user.id,now+SESSION_SECONDS,now).run();c.header('Set-Cookie',cookie(token));c.header('Cache-Control','no-store');return c.json({user:publicUser(user)})}
export async function register(c:Ctx){if(await throttled(c,'register',8))return c.json({error:'Too many attempts. Try again later.'},429);const parsed=registerSchema.safeParse(await readBody(c));if(!parsed.success)return c.json({error:'Enter a real name (2–60 letters and name separators), valid email, and a 12+ character password containing letters and numbers.'},400);const {name,email,password}=parsed.data;if(await c.env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return c.json({error:'An account with that email already exists.'},409);const id=crypto.randomUUID(),salt=randomHex(16),hash=await hashPassword(password,salt,ITERATIONS);try{await c.env.DB.batch([c.env.DB.prepare('INSERT INTO users(id,email,display_name) VALUES(?,?,?)').bind(id,email,name),c.env.DB.prepare('INSERT INTO auth_credentials(user_id,salt,hash,iterations) VALUES(?,?,?,?)').bind(id,salt,hash,ITERATIONS)])}catch{return c.json({error:'Could not create this account. Check the email and try again.'},409)}return issueSession(c,{id,email,display_name:name})}
export async function login(c:Ctx){if(await throttled(c,'login',12))return c.json({error:'Too many attempts. Try again later.'},429);const parsed=loginSchema.safeParse(await readBody(c));if(!parsed.success)return c.json({error:'Enter your email and password.'},400);const row=await c.env.DB.prepare('SELECT u.id,u.email,u.display_name,a.salt,a.hash,a.iterations FROM users u JOIN auth_credentials a ON a.user_id=u.id WHERE u.email=?').bind(parsed.data.email).first<User&{salt:string;hash:string;iterations:number}>();const actual=await hashPassword(parsed.data.password,row?.salt||'00000000000000000000000000000000',row?.iterations||ITERATIONS);if(!row||!equal(actual,row.hash))return c.json({error:'Incorrect email or password.'},401);return issueSession(c,row)}
export async function me(c:Ctx){const user=await currentUser(c);c.header('Cache-Control','no-store');return user?c.json({user:publicUser(user)}):c.json({user:null},401)}
export async function logout(c:Ctx){const token=getCookie(c.req.header('cookie'));if(token&&/^[a-f0-9]{64}$/.test(token))await c.env.DB.prepare('DELETE FROM auth_sessions WHERE token_hash=?').bind(await sha256(token)).run();c.header('Set-Cookie',cookie('',true));c.header('Cache-Control','no-store');return c.json({ok:true})}
